// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "ymd"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat/create": {
            "post": {
                "description": "チャット保存",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "チャット保存API",
                "parameters": [
                    {
                        "description": "チャット保存",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/chat.CreateChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chat.ChatResponse"
                        }
                    }
                }
            }
        },
        "/chat/delete": {
            "put": {
                "description": "ルーム内のチャットを削除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "チャット削除API",
                "parameters": [
                    {
                        "description": "ルームID",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/chat.DeleteChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/chat/get/{room_id}": {
            "get": {
                "description": "ルーム内のチャットを取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "チャット取得API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ルームID",
                        "name": "room_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/chat.ChatResponse"
                            }
                        }
                    }
                }
            }
        },
        "/create_profile": {
            "post": {
                "description": "プロフィール作成",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "プロフィール作成API",
                "parameters": [
                    {
                        "description": "プロフィール作成",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/user.UserProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "アプリケーションのログイン",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "ログインAPI",
                "parameters": [
                    {
                        "description": "サインアップ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.LonginResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "アプリケーションからログアウト",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "ログアウトAPI",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/room/create": {
            "post": {
                "description": "ルーム作成",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "ルーム作成API",
                "parameters": [
                    {
                        "description": "ルームID",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/room.RoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/room.RoomResponse"
                        }
                    }
                }
            }
        },
        "/signin": {
            "post": {
                "description": "ユーザー新規登録",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "ユーザー新規登録API",
                "parameters": [
                    {
                        "description": "サインアップ",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/user.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "ユーザー一覧取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "ユーザー一覧取得API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.UserListResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "chat.ChatResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "chat.CreateChatRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "roomId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "chat.DeleteChatRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "room.RoomRequest": {
            "type": "object",
            "properties": {
                "room_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "room.RoomResponse": {
            "type": "object",
            "properties": {
                "roomId": {
                    "type": "string"
                }
            }
        },
        "user.LonginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.UserListResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imagePath": {
                    "type": "string"
                },
                "roomId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "user.UserProfileRequest": {
            "type": "object",
            "properties": {
                "userName": {
                    "type": "string"
                }
            }
        },
        "user.UserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "homework API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
