version: "3.8"
services:
  homework:
    container_name: ${APP_NAME}
    build:
      context: ./src
      dockerfile: Dockerfile.local
    stdin_open: true
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
      APP_URL: ${APP_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PW: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      SECRET: ${SECRET}
      API_DOMAIN: ${API_DOMAIN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      GOOGLE_OAUTH_REDIRECT_URL: ${GOOGLE_OAUTH_REDIRECT_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    working_dir: /go/src
    volumes:
      - ./src:/go/src
    ports:
      - "${APP_PORT}:${APP_PORT}"
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 1m
    tty: true
    networks:
      - homework

  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - homework

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - homework

networks:
  homework:
    driver: bridge
